name: "Overwatch Mercy Meme"
source: https://imgflip.com/meme/223642538/Overwatch-Mercy-Meme
description: "A struggle followed by a rescue, with Overwatch's Mercy as the saviour. Top line is the struggle, bottom line is the help that arrives."
keywords:
  - "Overwatch"
  - "Mercy"
  - "Angela Ziegler"
  - "video game"
  - "Blizzard"
  - "savior"
  - "help"
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.00
    anchor_y: 0.00
    angle: 0.0
    scale_x: 1.00
    scale_y: 0.12
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.00
    anchor_y: 0.86
    angle: 0.0
    scale_x: 1.00
    scale_y: 0.12
    align: center
    start: 0.0
    stop: 1.0
example:
  - "Me struggling with my math homework"
  - "Photomath app"
