name: Member Berries
source: http://knowyourmeme.com/memes/member-berries
description: Nostalgic recall of something from the past, usually a half-remembered pop-culture item; top line is the recall, bottom line is the item.
keywords:
  - South Park
  - nostalgia
  - reminiscing
  - pop culture
  - forgotten memories
  - Star Wars
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - "'member"
  - star wars?
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
