name: The Most Interesting Man in the World
source: http://knowyourmeme.com/memes/the-most-interesting-man-in-the-world
description: Boasting in the 'I don't always X, but when I do, Y' format. Top line is what you rarely do, bottom line is how you do it.
keywords:
  - Dos Equis
  - Jonathan Goldsmith
  - I don't always
  - but when I do
  - beer commercial
  - boasting
  - self-importance
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - I don't often drink beer
  - so you shouldn't value my opinion
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
