name: Children Scared of Rabbit
source: https://imgflip.com/meme/257665044/Children-scared-of-rabbit
description: Two kids cowering against a wall in fear of a small, harmless animal. Top line is the kids' reaction, bottom line is what they are scared of.
keywords:
  - rabbit
  - bunny
  - scared
  - children
  - fear
  - overreaction
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
example:
  - When someone says the vet is coming
  - The bunny
