name: Life... Finds a Way
source: https://www.youtube.com/watch?v=dMjQ3hA9mEA
description: Saying that something will persist or happen anyway despite attempts to prevent it; the top line is the setup, and the bottom line is the persistent outcome.
keywords:
  - Jurassic Park
  - Ian Malcolm
  - Jeff Goldblum
  - persistence
  - unstoppable
  - resilience
  - inevitable outcome
  - loophole
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - life...
  - finds a way
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
