name: Blank Nut Button
source: https://imgflip.com/memetemplate/119139145
description: Being tempted by a button that the speaker is about to press, or a choice that comes with a big consequence. Top-left caption is the setup, bottom-right caption is the button's consequence.
keywords:
  - nut button
  - button
  - temptation
  - consequences
  - hand
  - choice
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.03
    angle: 0.0
    scale_x: 0.46
    scale_y: 0.22
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.55
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.44
    scale_y: 0.22
    align: center
    start: 0.0
    stop: 1.0
example:
  - When you see a good meme
  - Upvote
