name: 'Soyjak Pointing'
source: https://imgflip.com/meme/322540291/Soyjak-Pointing
description: 'Pointing out and mocking something, often an embarrassing or hypocritical thing. Left label is the shocked reaction, right label is the callout.'
keywords:
  - 'soyjak'
  - 'pointing'
  - 'mocking'
  - 'callout'
  - 'shocked'
  - 'hypocrisy'
  - 'reaction'
text:
  - style: none
    color: black
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.44
    scale_y: 0.11
    align: center
    start: 0.0
    stop: 1.0
  - style: none
    color: black
    font: thick
    anchor_x: 0.55
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.44
    scale_y: 0.09
    align: center
    start: 0.0
    stop: 1.0
example:
  - 'HE SAYS HE NEVER READS THE DOCS'
  - 'HE LINKED THE DOCS IN HIS PR'
