name: Expectation vs. Reality
source: https://knowyourmeme.com/memes/disappointed-black-guy
description: Contrasting a hopeful expectation with a disappointing reality. Top line is what was expected, bottom line is the letdown.
keywords:
  - Disappointed Black Guy
  - letdown
  - false hope
  - bait and switch
  - disillusionment
  - unmet expectations
  - advertising
text:
  - style: default
    color: black
    font: thin
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.5
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: black
    font: thin
    anchor_x: 0.0
    anchor_y: 0.5
    angle: 0.0
    scale_x: 0.48
    scale_y: 0.5
    align: center
    start: 0.0
    stop: 1.0
example:
  - Clicking the 'X' on a mobile ad
  - The 'X' is part of the ad
overlay:
  - center_x: 0.25
    center_y: 0.245
    angle: 0.0
    scale: 0.492
    start: 0.0
    stop: 1.0
  - center_x: 0.25
    center_y: 0.75
    angle: 0.0
    scale: 0.5
    start: 0.0
    stop: 1.0
