name: "Sad Hamster"
source: https://imgflip.com/meme/511654183/Sad-Hamster
description: "A small hamster with big sad eyes, used for something pitiful or tiring. Top line is the setup, bottom line is the sad reaction."
keywords:
  - "sad hamster"
  - "hamster"
  - "pet"
  - "sad"
  - "pitiful"
  - "cute"
  - "taxes"
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.00
    anchor_y: 0.00
    angle: 0.0
    scale_x: 1.00
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.00
    anchor_y: 0.84
    angle: 0.0
    scale_x: 1.00
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
example:
  - "me when i have to do my taxes"
  - "i'm just a baby"
