name: Baby Insanity Wolf
source: http://knowyourmeme.com/memes/baby-insanity-wolf
description: Harmless, childish behavior framed as wild rebellion, a mild version of Insanity Wolf. Top line is the setup, bottom line is the tame 'insane' act.
keywords:
  - Insanity Wolf
  - wolf pup
  - howling
  - tame rebellion
  - childish
  - mild extremes
  - absurd behavior
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - gets iced coffee
  - in the winter
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
