name: That Would Be Great
source: http://knowyourmeme.com/memes/that-would-be-great
description: Sarcastic, grudging agreement to a request you won't follow through on; top line is the reluctant yeah, bottom line is the pointed sign-off.
keywords:
  - Office Space
  - Milton
  - Stephen Root
  - sarcasm
  - passive aggression
  - reluctant agreement
  - ignoring requests
  - dismissive
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - yeah...
  - that'd be great
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
