name: Agnes Harkness Winking
source: https://knowyourmeme.com/memes/agnes-harkness-winking
description: Pretending to have read or agreed to something, such as terms and conditions, while clearly not meaning it; the bottom line is the false claim.
keywords:
  - WandaVision
  - Kathryn Hahn
  - Agatha
  - Terms and Conditions
  - fine print
  - pretending
  - false agreement
  - not reading
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - ''
  - i have read and agree to the terms and conditions
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
