name: Drowning High Five
source: https://knowyourmeme.com/memes/drowning-high-five
description: Asking for help and getting a sympathetic but useless reply. First line is the plea, second the commenter, third the empty 'me too' response.
keywords:
  - me too
  - unhelpful advice
  - sympathy
  - online comments
  - relatable
  - no help
  - pointless response
text:
  - style: default
    color: white
    font: impact
    anchor_x: 0.03
    anchor_y: 0.33
    angle: 0.0
    scale_x: 0.46
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: impact
    anchor_x: 0.51
    anchor_y: 0.14
    angle: 0.0
    scale_x: 0.2
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: khaki
    font: impact
    anchor_x: 0.03
    anchor_y: 0.82
    angle: 0.0
    scale_x: 0.46
    scale_y: 0.15
    align: center
    start: 0.4
    stop: 1.0
example:
  - Me Asking for Help
  - Online Commenter
  - I'm having that problem too.
overlay:
  - center_x: 0.585
    center_y: 0.14
    angle: 0.0
    scale: 0.2
    start: 0.0
    stop: 1.0
