name: Y U NO Guy
source: http://knowyourmeme.com/memes/y-u-no-guy
description: Angrily asking why someone did not do something you expected or wanted from them. Top line is the complaint; bottom line is what they should have done.
keywords:
  - frustration
  - exasperation
  - indignation
  - demanding
  - rage
  - why didn't you
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - y u no
  - use this meme!?
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
