name: "Weak vs Strong Spongebob"
source: https://imgflip.com/meme/174791714/Weak-vs-Strong-Spongebob
description: "Contrasting a weak, unimpressive version of something with an overpowered, muscular one. Top line is the weak option, bottom line is the strong option."
keywords:
  - "SpongeBob"
  - "weak vs strong"
  - "comparison"
  - "muscles"
  - "transformation"
  - "glow up"
  - "upgrade"
  - "power"
text:
  - style: none
    color: black
    font: thick
    anchor_x: 0.52
    anchor_y: 0.12
    angle: 0.0
    scale_x: 0.45
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: none
    color: black
    font: thick
    anchor_x: 0.52
    anchor_y: 0.62
    angle: 0.0
    scale_x: 0.45
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - "Reading the instructions"
  - "Reading the source code"
