name: Disaster Girl
source: http://knowyourmeme.com/memes/disaster-girl
description: Smug, self-satisfied reaction to a disaster you caused or foresaw. The bottom line is the smirk-worthy admission that it went exactly to plan.
keywords:
  - smug
  - schadenfreude
  - mischief
  - success through chaos
  - satisfaction
  - gleeful
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - ''
  - just as I planned...
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
