name: Dr. Robotnik Waving
description: Gleefully waving goodbye as you make a smug exit or get away with something. Top line is the situation; bottom line is the triumphant send-off.
keywords:
  - Sonic the Hedgehog
  - Jim Carrey
  - Dr. Eggman
  - waving goodbye
  - smug exit
  - getting away with it
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.005
    anchor_y: 0.005
    angle: 0.0
    scale_x: 0.99
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.005
    anchor_y: 0.79
    angle: 0.0
    scale_x: 0.99
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - me leaving at 5pm sharp
  - good luck with the deploy!
