name: 'Spongebob Yelling'
source: https://imgflip.com/meme/231672072/Spongebob-Yelling
description: 'Yelling in frustration or desperation at a situation that has gone badly. Top line is the setup, bottom line is the outburst.'
keywords:
  - 'spongebob'
  - 'yelling'
  - 'angry'
  - 'frustration'
  - 'shouting'
  - 'crowd'
  - 'panic'
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.84
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.13
    align: center
    start: 0.0
    stop: 1.0
example:
  - 'WHEN THE WIFI DROPS MID-CALL'
  - 'AND I''M ON CAMERA'
