name: Anime Girl Hiding From Terminator
source: https://imgflip.com/memetemplate/224514655
description: "Hiding in fear from something menacing or inevitable. Top line is the situation, bottom line is the fear."
keywords:
  - anime
  - Terminator
  - hiding
  - fear
  - scared
  - crying
  - dread
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.3
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.68
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.84
    angle: 0.0
    scale_x: 0.95
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
example:
  - "When my boss walks in"
  - "And asks about the report"
