name: Captain Kirk Khan
source: https://imgflip.com/meme/100708178/Captain-Kirk-Khan
description: An explosive, furious outburst, a reference to Captain Kirk's "KHAAAN!" from Star Trek II. Top line is the setup, bottom line is the outburst.
keywords:
  - Captain Kirk
  - Khan
  - Star Trek
  - rage
  - scream
  - outburst
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.02
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.02
    anchor_y: 0.84
    angle: 0.0
    scale_x: 0.96
    scale_y: 0.14
    align: center
    start: 0.0
    stop: 1.0
example:
  - When the build breaks in production
  - KHAAAAN!
