name: I Guarantee It
source: http://knowyourmeme.com/memes/george-zimmer-i-guarantee-it
description: Confidently promising that someone will be pleased with a purchase or change; top line describes the expected result, bottom line is the guarantee.
keywords:
  - George Zimmer
  - Men's Wearhouse
  - sales pitch
  - reassurance
  - confident promise
  - satisfaction
  - ad campaign
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - you're gonna like the way you look
  - i guarantee it
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
