name: Jojo Walk
description: Someone approaching menacingly and with style to deal with a situation. Top line is who or what is walking up; bottom line is where they are heading.
keywords:
  - JoJo's Bizarre Adventure
  - Risotto Nero
  - anime
  - menacing approach
  - walking in
  - here I come
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.005
    anchor_y: 0.005
    angle: 0.0
    scale_x: 0.99
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.005
    anchor_y: 0.84
    angle: 0.0
    scale_x: 0.99
    scale_y: 0.15
    align: center
    start: 0.0
    stop: 1.0
example:
  - me walking to the kitchen
  - at 3 am
