name: The Worst Day Of Your Life So Far
source: https://knowyourmeme.com/memes/the-worst-day-of-your-life-so-far
description: Insisting someone else's bad day is even worse, a sarcastic one-up on a complaint. Top line is the complaint; bottom line is the mocking one-up.
keywords:
  - Bart Simpson
  - Homer Simpson
  - The Simpsons
  - one-upping
  - dark humor
  - sarcasm
  - escalation
text:
  - style: default
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.4
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.9
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
example:
  - This is the worst day of my life.
  - This is the worst day of your life so far.
overlay:
  - center_x: 0.485
    center_y: 0.1
    angle: 0.0
    scale: 0.2
    start: 0.0
    stop: 1.0
