name: I'm Going to Build My Own Theme Park
source: 
  http://knowyourmeme.com/memes/im-going-to-build-my-own-theme-park-with-blackjack-and-hookers
description: Announcing an outlandish plan, with the bottom line adding an absurd detail; the top line is the plan, and the bottom line is the ridiculous addition.
keywords:
  - Futurama
  - Bender
  - Bender Bending Rodriguez
  - absurd plan
  - outlandish
  - gambling
  - ambition
  - vice
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - i'm going to build my own theme park
  - with blackjack and hookers
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
