name: I See Dead People
source: https://imgflip.com/meme/155967260/Sixth-Sense
description: 'Scared, whispered admission of seeing something others don''t. Top line is the confession; bottom line is the twist.'
keywords:
  - The Sixth Sense
  - Haley Joel Osment
  - I see dead people
  - scared
  - whisper
  - confession
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.005
    anchor_y: 0.005
    angle: 0.0
    scale_x: 0.99
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.005
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.99
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
example:
  - I see dead code
  - 'they don''t know they''re dead'
