name: Winter is coming
source: 
  http://knowyourmeme.com/memes/imminent-ned-brace-yourselves-winter-is-coming
description: Warning someone to brace for an inevitable, ominous event that is coming. Top line is the setup; bottom line is the grim warning.
keywords:
  - Ned Stark
  - Game of Thrones
  - Imminent Ned
  - foreboding
  - ominous warning
  - impending doom
  - dramatic warning
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - prepare yourself
  - winter is coming
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
