name: Facepalm
source: http://knowyourmeme.com/memes/facepalm
description: Reacting to something absurd or embarrassing with exasperated disbelief; the bottom line is the caption of that reaction.
keywords:
  - Picard
  - Star Trek
  - Patrick Stewart
  - exasperation
  - disbelief
  - embarrassment
  - frustration
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - ''
  - I can't even
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
