name: Stonks
source: https://knowyourmeme.com/memes/stonks
description: Sarcastically praising a dubious or irrational decision that happens to be paying off. Single caption line is the praise.
keywords:
  - Meme Man
  - stock market
  - investing
  - irony
  - dubious success
  - bad investment
  - sarcasm
  - finance
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - ''
  - stonks
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
