name: Confused Gandalf
source: http://knowyourmeme.com/memes/confused-gandalf
description: Expressing bewildered confusion at a familiar place or situation and claiming no memory of it; the bottom line is the claim.
keywords:
  - Lord of the Rings
  - Ian McKellen
  - amnesia
  - forgetting
  - disorientation
  - deja vu
  - lost
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - ''
  - I have no memory of this place
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
