name: For Dummies Book
source: https://imgflip.com/meme/131099891/For-dummies-book
description: A parody of the For Dummies book series that frames a topic as so simple that even a beginner can learn it. Top line is the topic, bottom line is the reassuring (often ironic) tagline.
keywords:
  - for dummies
  - book cover
  - beginner
  - tutorial
  - easy
  - reference guide
  - yellow
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.1
    angle: 0.0
    scale_x: 0.88
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.556
    anchor_y: 0.52
    angle: 0.0
    scale_x: 0.44
    scale_y: 0.24
    align: center
    start: 0.0
    stop: 1.0
example:
  - MEME MAKING
  - It's easy!
