name: The Office Handshake
source: https://imgflip.com/meme/206622427/the-office-handshake
description: Being congratulated or praised for something you have no memory of doing. Top line is the boss congratulating you, bottom line is you with no idea what happened.
keywords:
  - the office
  - handshake
  - michael scott
  - ed truck
  - young michael scott
  - mullet
  - confused praise
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.03
    anchor_y: 0.72
    angle: 0.0
    scale_x: 0.42
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.52
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.46
    scale_y: 0.18
    align: center
    start: 0.0
    stop: 1.0
example:
  - My boss congratulating me
  - Me who has no idea what I did
