name: Genie Lamp
source: https://imgflip.com/memetemplate/205390462
description: Contrasting a grand claim of power or ability with a cramped, humble reality; top line is the grand claim, bottom the reality.
keywords:
  - Aladdin
  - Disney
  - Robin Williams
  - contrast
  - cramped quarters
  - humble reality
  - irony
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - phenomenal cosmic power
  - itty bitty living space
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
