name: Skeptical Third World Kid
source: http://knowyourmeme.com/memes/third-world-success
description: 'Doubtful, sarcastic pushback on a claim that seems suspiciously obvious: top line is the claim, bottom line is the skeptical reply.'
keywords:
  - side-eye
  - doubt
  - suspicion
  - rhetorical question
  - sarcasm
  - obvious answer
  - incredulity
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - you finished your plate
  - because i was starving?
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
