name: What Are Ya Gonna Do?
source: https://www.youtube.com/watch?v=76URh0S7YIw
description: Shrugging off a situation with resigned indifference and asking what can be done about it. Top line is a sigh; bottom line is the resigned question.
keywords:
  - shrug
  - resignation
  - indifference
  - helplessness
  - nothing to be done
  - casual acceptance
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - yeah...
  - what are ya gonna do?
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
