name: No Soup for You
source: https://knowyourmeme.com/memes/no-soup-for-you-soup-nazi
description: 'Flatly denying someone access to something because they broke a rigid rule: the line is the stern, dismissive refusal.'
keywords:
  - Seinfeld
  - Soup Nazi
  - Larry Thomas
  - rigid rules
  - denial
  - strict rules
  - angry refusal
text:
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: impact
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - no soup for you!
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
