name: The Future World If
source: https://imgflip.com/meme/179137533/The-future-world-if
description: Describing an idealized future society that would exist if some change happened, usually as a joke about how much better everything would be. The caption completes the sentence at the top.
keywords:
  - the world if
  - society if
  - future
  - utopia
  - futuristic city
  - utopian
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.01
    anchor_y: 0.002
    angle: 0.0
    scale_x: 0.98
    scale_y: 0.148
    align: center
    start: 0.0
    stop: 1.0
example:
  - The world if everyone used the correct meme template
aliases:
  - futuristic-utopia
  - society-if
