name: What Color Do You Want Your Dragon
source: https://knowyourmeme.com/photos/1052192-tumblr
description: Lowering an unrealistic wish to a more realistic, personal one after being told to be practical. The single line is the revised, modest wish.
keywords:
  - wish
  - Santa Claus
  - Christmas
  - lowered expectations
  - compromise
  - realistic expectations
  - dating
text:
  - style: upper
    color: black
    font: comic
    anchor_x: 0.22
    anchor_y: 0.505
    angle: 0.0
    scale_x: 0.25
    scale_y: 0.119
    align: center
    start: 0.0
    stop: 1.0
example:
  - OK I want a boyfriend
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
    start: 0.0
    stop: 1.0
